INSERT INTO PERSON (NAME, AGE) VALUES ('Alice', 30);
INSERT INTO PERSON (NAME, AGE) VALUES ('Bob', 25);
INSERT INTO PERSON (NAME, AGE) VALUES ('Charlie', 35);
INSERT INTO PERSON (NAME, AGE) VALUES ('Diana', 28);
INSERT INTO PERSON (NAME, AGE) VALUES ('Ethan', 40);

